apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-gradle
  labels:
    app: skaffold-gradle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skaffold-gradle
  template:
    metadata:
      labels:
        app: skaffold-gradle
    spec:
      containers:
        - name: skaffold-gradle
          image: bonescorp/skaffold-gradle:latest
          imagePullPolicy: Never
          ports:
          - name: liveness-port
            containerPort: 8080
            hostPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health
              port: liveness-port
            failureThreshold: 30
            periodSeconds: 10