apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: springboot-skaffold
build:
  #tagPolicy:
   # envTemplate:
    #  template: "{{.VERSION}}"
  artifacts:
  - image: bonescorp/skaffold-gradle
    custom:
      buildCommand: gradlew clean build buildImage
deploy:
  kubectl:
    manifests:
    - kubernetes.yaml
    #hooks:
     # after:
      #  - container:
      #      command: [ "curl", "-v", "http://localhost:8080/actuator" ]
      #      podName: skafford-gradle-*
      #      containerName: skafford-gradle

#portForward:
 # - resourceType: pod
  #  resourceName: skafford-gradle
   # namespace: default
   # port: 8080
   # localPort: 8080
